#!/usr/bin/env bash

./package.sh

rm ~/Documents/School/ICERM/sage/upstream/pf_addcomb-0.1.tar.gz
cp ~/Documents/Projects/math/pf_addcomb/pf_addcomb-0.1.tar.gz ~/Documents/School/ICERM/sage/upstream/pf_addcomb-0.1.tar.gz

rm -r /home/matt/Documents/School/ICERM/sage/build/pkgs/pf_addcomb

mkdir /home/matt/Documents/School/ICERM/sage/build/pkgs/pf_addcomb
tar -C /home/matt/Documents/School/ICERM/sage/build/pkgs/pf_addcomb -zxvf ./pf_addcomb-0.1.tar.gz

sage --fix-pkg-checksums

sage -p pf_addcomb-0.1.spkg
