sudo: false
language: rust
cache: cargo
rust:
- nightly
- beta
- stable
env:
  global:
    - FEATURES=yaml_enc,bin_enc,ron_enc,mmap
script:
- |
  cargo build --features $FEATURES &&
  cargo test --features $FEATURES &&
  cargo doc --features $FEATURES
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
